### ISSUE TITLE
sha256: digests do not match test vectors

### ISSUE THREAD

**Issue by cyphar** [jgoerzen/libnbcompat#4]
I'm not sure where this port is used, but you should probably be aware of the issue with sha256 digests I found and debugged in archiecobbs/libnbcompat#4. The short version is that there is a strict aliasing violation in `sha2.c` which newer GCC versions (gcc 11 and newer) will optimise in a way that causes `SHA256_Final` to output incorrect sha256 hashes on most inputs.

The fix is fairly minimal and can be seen in archiecobbs/libnbcompat@864c1cf42c2c605636008626f171caf6410421cb.

**Comment by jgoerzen** [comment]
Thanks; this has been pulled in with the newer nbcompat.
